### ISSUE TITLE
ILI9341 Arduino Uno shield

### ISSUE THREAD

**Issue by SKEW002** [elmouden007/STM32TFT#2]
Hi, may I know will this works for ILI9341 Arduino Uno shield? If yes, may I know how should I connect it to STM32?

This is the screen I am using:
http://qqtrading.com.my/2-4-tft-touch-screen-lcd-ili9341

Thank you

**Comment by elmouden007** [comment]
You mean tft shield ? Uf yes send me a picture with pinout

**Comment by SKEW002** [comment]
![image](https://user-images.githubusercontent.com/57441569/121023008-73d17380-c7d5-11eb-8933-e7272cbbfd3f.jpg)

**Comment by elmouden007** [comment]
Sent from my iPhone

> On Jun 7, 2021, at 14:16, SKEW002 ***@***.***> wrote:
> 
No this modul is very old . It need many pins . I have no idea about if it work or not

**Comment by SKEW002** [comment]
It's ok, thanks for your reply
